# Конфиги 8 пересобранных версий ролика «В основе любой нейросети — математика».
# Сцены: hook, myth, tokens, space(ex), prob, train, gen, w2n, punch, share, loop (последние ~2 с: закольцовка на хук + CTA).
SHARE_MATH = 'Отправьте тому, кто говорил, что математика не пригодится'
SHARE_KID = 'Отправьте школьнику'
SHARE_KNOW = 'Отправьте тому, кто думает, что ChatGPT всё знает'

def S(t, d, **k):
    return dict(type=t, d=d, **k)

V = [
 dict(id='MATHR1', order=1, kind='short', start='с числа',
      hook=dict(style='numbers', lines=['Внутри ChatGPT', 'нет ни одного', 'слова'], size=104),
      title='Внутри ChatGPT нет ни одного слова', cover=dict(lines=['Внутри ChatGPT', 'ни одного', 'слова'], size=110),
      pal=dict(bg0='#020805', bg1='#0b2416', a='#3dff9a', b='#b6ff5c', hot='#ff5c7a', ok='#7dffb0', txt='#eafff2', dim='#7fa894'),
      palname='зелёная «матрица»', bg='rain', zoom=1.0, myth='cards', probStyle='h', seed=11,
      tokens=['Стол', 'ица', ' Фран', 'ции', ' —'], share=SHARE_KNOW,
      mythLine='Кажется, ChatGPT хранит готовые ответы', audio='pulse',
      scenes=[S('hook', 2.6), S('tokens', 5.5), S('myth', 4.0), S('prob', 5.5), S('train', 5.0), S('w2n', 3.2), S('punch', 2.4), S('share', 2.2), S('loop', 2.0)]),
 dict(id='MATHR2', order=2, kind='long', start='с мифа (полный путь)',
      hook=dict(style='formula', lines=['В основе любой нейросети —', 'математика'], size=150),
      title='В основе любой нейросети — математика', cover=dict(lines=['В основе нейросети —', 'математика'], size=150),
      pal=dict(bg0='#0a0503', bg1='#2a1608', a='#ffb347', b='#ff7a45', hot='#ff4f8b', ok='#8dff9e', txt='#fff4e6', dim='#b79a7e'),
      palname='тёплая янтарная', bg='dust', zoom=0.92, myth='shelves', probStyle='h', seed=23,
      tokens=['Нейро', 'сеть', ' счи', 'тает'], share=SHARE_MATH, audio='pad',
      scenes=[S('hook', 2.8), S('myth', 6.5), S('tokens', 6.5), S('space', 7.0, ex='paris'), S('prob', 5.5), S('space', 5.5, ex='cats'),
              S('train', 7.0), S('gen', 7.0), S('w2n', 3.8), S('punch', 2.8), S('share', 2.5), S('loop', 2.1)]),
 dict(id='MATHR3', order=3, kind='short', start='с вопроса-загадки',
      hook=dict(style='question', lines=['Париж или трактор?', 'Решает математика'], size=92, cols=[None, 'grad']),
      title='Париж или трактор? Решает математика', cover=dict(lines=['Париж или трактор?', 'Решает математика'], size=92),
      pal=dict(bg0='#08030a', bg1='#2a0b2e', a='#ff5cd6', b='#9b7bff', hot='#ffb03b', ok='#6dffb0', txt='#fff0fb', dim='#b08fb0'),
      palname='пурпурно-розовая', bg='rings', zoom=1.12, myth='shelves', probStyle='v', seed=37,
      tokens=['Стол', 'ица', ' Фран', 'ции', ' —'], share=SHARE_KID,
      mythLine='Думали, ChatGPT ищет ответ в библиотеке?', audio='arp',
      scenes=[S('hook', 2.6), S('prob', 5.5), S('myth', 4.0), S('tokens', 4.8), S('train', 4.6), S('punch', 2.4), S('share', 2.2), S('loop', 2.0)]),
 dict(id='MATHR4', order=4, kind='long', start='с мифа',
      hook=dict(style='library', lines=['Нет никакой', 'библиотеки', 'ответов'], size=116),
      title='Нет никакой библиотеки ответов', cover=dict(lines=['Нет никакой', 'библиотеки', 'ответов'], size=120),
      pal=dict(bg0='#02070b', bg1='#082433', a='#5ef0ff', b='#4f8bff', hot='#ff6b6b', ok='#7dffb4', txt='#eefcff', dim='#86a9b8'),
      palname='ледяная бирюзовая', bg='rain', zoom=1.0, myth='shelves', probStyle='h', seed=41,
      tokens=['Мос', 'ква', ' бли', 'же', ' к'], share=SHARE_KNOW, audio='glass',
      mythLine='Многие думают: внутри ChatGPT — огромная библиотека готовых ответов',
      scenes=[S('hook', 2.8), S('myth', 6.5), S('tokens', 6.5), S('space', 7.5, ex='cities'), S('prob', 5.5), S('train', 7.0),
              S('w2n', 3.8), S('punch', 2.8), S('share', 2.5), S('loop', 2.1)]),
 dict(id='MATHR5', order=5, kind='short', start='с панчлайна',
      hook=dict(style='chalk', lines=['Зачем вам алгебра?', 'Вот зачем'], size=100, cols=[None, 'grad']),
      title='Зачем вам алгебра? Вот зачем', cover=dict(lines=['Зачем вам алгебра?', 'Вот зачем'], size=100),
      pal=dict(bg0='#050814', bg1='#142042', a='#ffe45c', b='#7fd1ff', hot='#ff6b81', ok='#8dff9e', txt='#fdfbf0', dim='#8f9bbf'),
      palname='«школьная доска»: жёлтый мел на синем', bg='grid', zoom=1.08, myth='shelves', probStyle='h', seed=53,
      tokens=['За', 'чем', ' ал', 'гебра', '?'], share=SHARE_KID, audio='lofi',
      scenes=[S('hook', 2.6), S('myth', 4.4), S('tokens', 5.2), S('prob', 5.2), S('train', 5.2), S('w2n', 3.0), S('punch', 2.6), S('share', 2.2), S('loop', 2.0)]),
 dict(id='MATHR6', order=6, kind='long', start='с числа (вопрос → числа)',
      hook=dict(style='chat', lines=['Ваш вопрос ChatGPT', 'превращает в числа'], size=90, cols=[None, 'grad']),
      title='Ваш вопрос ChatGPT превращает в числа', cover=dict(lines=['Ваш вопрос —', 'это числа'], size=120),
      pal=dict(bg0='#06040f', bg1='#1d1240', a='#c08bff', b='#6ee7ff', hot='#ff7a59', ok='#7dffb0', txt='#f3eeff', dim='#9d93c7'),
      palname='фиолетово-голубая', bg='dust', zoom=0.95, myth='cards', probStyle='v', seed=67,
      tokens=['Стол', 'ица', ' Фран', 'ции', '?'], share=SHARE_MATH, audio='organ',
      mythLine='А вы думали, там база готовых ответов?',
      scenes=[S('hook', 2.8), S('tokens', 6.0), S('myth', 5.0), S('space', 6.5, ex='cats'), S('prob', 5.5), S('train', 6.5),
              S('gen', 6.5), S('punch', 2.6), S('share', 2.4), S('loop', 2.0)]),
 dict(id='MATHR7', order=7, kind='short', start='с мифа (поиск)',
      hook=dict(style='search', lines=['ChatGPT не ищет ответ.', 'Он считает'], size=88, cols=[None, 'grad']),
      title='ChatGPT не ищет ответ. Он считает', cover=dict(lines=['ChatGPT не ищет.', 'Он считает'], size=100),
      pal=dict(bg0='#0c0405', bg1='#2e0f12', a='#ff6b5b', b='#ffc15c', hot='#7aa2ff', ok='#7dffb0', txt='#fff1ee', dim='#c09a96'),
      palname='коралловая', bg='lines', zoom=1.08, myth='cards', probStyle='h', seed=79,
      tokens=['Он', ' счи', 'тает'], share=SHARE_KNOW, audio='tick',
      mythLine='Кажется, ChatGPT достаёт ответ из огромной базы',
      scenes=[S('hook', 2.5), S('myth', 4.0), S('tokens', 4.2), S('prob', 5.0), S('train', 4.4), S('punch', 2.4), S('share', 2.2), S('loop', 2.0)]),
 dict(id='MATHR8', order=8, kind='long', start='с числа (формула)',
      hook=dict(style='equation', lines=['Нейросеть — это', 'алгебра', 'из 9-го класса'], size=100, cols=[None, 'grad', None]),
      title='Нейросеть — это алгебра из 9-го класса', cover=dict(lines=['Нейросеть —', 'алгебра', '9-го класса'], size=110),
      pal=dict(bg0='#020a0c', bg1='#0a2a2e', a='#4dfff0', b='#d4ff5c', hot='#ff5c8a', ok='#9dff7a', txt='#ecffff', dim='#84aeb0'),
      palname='бирюзово-лаймовая', bg='grid', zoom=1.05, myth='shelves', probStyle='v', seed=97,
      tokens=['Кош', 'ка', ' спит', ' на'], share=SHARE_KID, audio='chip',
      mythLine='Внутри ChatGPT нет библиотеки готовых ответов',
      scenes=[S('hook', 2.8), S('tokens', 5.5), S('space', 7.0, ex='cities'), S('myth', 4.5), S('prob', 5.0), S('train', 6.0),
              S('w2n', 3.6), S('punch', 2.8), S('share', 2.4), S('loop', 2.0)]),
]
for v in V:
    v['dur'] = round(sum(s['d'] for s in v['scenes']), 2)
